// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M_basicinformation_Addanddelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M_basicinformation_Addanddelete));
        
        string IMigrationMetadata.Id
        {
            get { return "202007090612097_M_basic information _Add and delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
