// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PurchaseAdd_Z_Row_Null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PurchaseAdd_Z_Row_Null));
        
        string IMigrationMetadata.Id
        {
            get { return "202007130500109_Purchase-Add_Z_Row_Null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
