// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ly34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ly34));
        
        string IMigrationMetadata.Id
        {
            get { return "202006240212459_ly-34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
