// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aDD_DEL_or : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aDD_DEL_or));
        
        string IMigrationMetadata.Id
        {
            get { return "202007170437082_aDD_DEL_or"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
