// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creat_Able : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creat_Able));
        
        string IMigrationMetadata.Id
        {
            get { return "202007200316348_creat_Able"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
