// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M_basicinformationAdd_Finshed_Sign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M_basicinformationAdd_Finshed_Sign));
        
        string IMigrationMetadata.Id
        {
            get { return "202007100723479_M_basic information Add_Finshed_Sign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
