// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mzy_AddCom1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mzy_AddCom1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007210427387_mzy_AddCom1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
