// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class My_5_EditUser_user_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(My_5_EditUser_user_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "202007030725192_My_5_ Edit - User_user_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
