// <auto-generated />
namespace XiAnOuDeERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mzy_Update_Position1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mzy_Update_Position1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007240857180_Mzy_Update_Position1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
